# DON'T FORGET TO RUN `pre-commit install` to set up the pre-commit hooks

# Eligible files:
#     python: .py files

# To run on all eligible files: 
#       pre-commit run --all-files

# If used as pre-commit hook, will only
# be applied to staged files
repos:
  - repo: local
    hooks:
    - id: ruff
      name: ruff
      description: "ruff: Python linting"
      entry: ruff check . --fix
      language: python
      types_or: [python]
      require_serial: true
    - id: ruff-format
      name: ruff-format
      description: "ruff: Python formatting"
      entry: ruff format .
      language: python
      types_or: [python]
      require_serial: true
    - id: mypy
      name: mypy
      description: "mypy"
      entry: mypy --disallow-untyped-calls
      language: python
      types_or: [python]
      require_serial: true