[tool.ruff]

# Same as Black.
line-length = 99
indent-width = 4

# Assume Python 3.11
# Options: https://docs.astral.sh/ruff/settings/#target-version
target-version = "py311"

[tool.ruff.lint]

select = [
    # defaults
    "E4",
    "E7",
    "E9",
    "F",
    # isort
    "I",
    # pydocstyle
    "D",
    # pyupgrade
    "UP",
    # pep8-naming
    "N",]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]

# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.mypy]
# Do not report an error if no type annotations for an imported module
# useful when working with third-party libraries that don't have type stubs
ignore_missing_imports = true